**Could refer to Obsidian for the information of how the examples work.**

---

## Example 1.
`np.where(condition, x, y)`

In [2]:
import numpy as np

In [3]:
np.where([[True, False], [True, True]],   # cond
         [[1111, 22222], [3333, 44444]],  # x
         [[9999, 88888], [7777, 66666]])  # y

array([[ 1111, 88888],
       [ 3333, 44444]])

## Example 2.
`np.where(condition, x, y)`

In [4]:
np.where([[True, False], [True, True]],
         [[1111, 22222], [3333, 44444]],
         5)

array([[ 1111,     5],
       [ 3333, 44444]])

## Example 3.
`np.where(condition, x, y)`

In [5]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])
np.where(x < 5, x, 100)

array([[  0,   1,   2],
       [  3,   4, 100],
       [100, 100, 100]])

## Example 4.
`np.where(condition)`

In [6]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]])
np.where(x)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [7]:
y = np.array([[0,1,2],[3,4,5],[6,6,6]])
np.where(y)

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))